### ISSUE TITLE
Possible bug in qualifier value range slot_usage access in some biolink:Association subclasses

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model-toolkit#147]
A curious defect was noticed in qualifier value **`range`** **`slot_usage`** access in some **`biolink:Association`** subclasses.

The specific anomaly noted from accessing the following in the Biolink class:

```yaml
  chemical affects gene association:
...
    slots:
...
      - object part qualifier
      - object aspect qualifier
...
    slot_usage:
...
      object part qualifier:
        range: GeneOrGeneProductOrChemicalPartQualifierEnum
      object aspect qualifier:
        range: GeneOrGeneProductOrChemicalEntityAspectEnum
```

Note that the object aspect qualifier range recorded in the model is **`GeneOrGeneProductOrChemicalEntityAspectEnum`**.

However, when using an toolkit class instance 'bmt' (e.g. from release 3.5.2)

```python
association_element = bmt.get_element("biolink:ChemicalAffectsGeneAssociation")
qualifier_type = association_element["slot_usage"]["object aspect qualifier"]
value_range = qualifier_type.range
```
one gets the following

```python
 value_range == GeneOrGeneProductOrChemicalPartQualifierEnum
```

which seems to be the value of the **`range`** of the preceding **`object part qualifier`** entry, not the expected **`GeneOrGeneProductOrChemicalEntityAspectEnum`** range enum for **`object aspect qualifier`**.  This, of course, causes reasoner validation false positive errors. Here's one known example of this:

```yaml
"errors": {
      "error.knowledge_graph.edge.qualifiers.qualifier.value.unresolved": {
        "infores:lincs -> infores:improving-agent": {
          "activity_or_abundance": [
            {
              "edge_id": "NCBIGene:57019[biolink:Gene]--biolink:regulates->NCBIGene:310[biolink:Gene]",
              "qualifier_type_id": "biolink:object_aspect_qualifier"
            } ...
```

which has an matches to **`chemical affects gene association`** but fails to be validated inside **`bmt.validate_qualifier()`** (in code similar to the above).
