### ISSUE TITLE
slots conflicting with predicates?

### ISSUE THREAD

**Issue by cbizon** [biolink/biolink-model-toolkit#19]
I'm not sure if this is a BMT or model problem (or usage problem for that matter).

There are two "has output"s in the model.  One is a predicate:

```
has output:
    is_a: has participant
    description: >-
      holds between a process and a continuant, where the continuant is an output of the process
    domain: occurrent
    in_subset:
      - translator_minimal
    close_mappings:
      # RTX inverse mapping to to 'biolink:has_output'
      - RO:0002353
      - RO:0002354
      - RTXKG1:output_of
    exact_mappings:
      - RO:0002234
    narrow_mappings:
      - NCIT:biological_process_has_result_anatomy
```

And there is also a slot with that name:
```
molecular activity:
    is_a: biological process or activity
    aliases: ['molecular function', 'molecular event', 'reaction']
    mixins:
      - occurrent
    description: >-
      An execution of a molecular function carried out by a gene product or macromolecular complex.
    slot_usage:
      has input:
        range: chemical substance
        description: >-
          A chemical entity that is the input for the reaction
      has output:
        range: chemical substance
        description: >-
          A chemical entity that is the output for the reaction
```

So first, I'm not sure what to make of that, but...

If I try to use the toolkit to get all descendants of "related to":
`bmt_toolkit.get_descendants('related to')`

I get a whole bunch of stuff including 
```
...'has output', 'molecular activity_has output',...
```
including both versions of has output.  I think that the second one should not be there? But...

If I now try to get descendants of these things:
```
>>> bmt_toolkit.get_descendants('has output')
['has output', 'molecular activity_has output']
```
which posits a weird relationship between the slot and the predicate?

And finally the bug:
```
>>> bmt_toolkit.get_descendants('molecular activity_has output')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/bl_lookup/lib/python3.8/site-packages/bmt/toolkit.py", line 298, in get_descendants
    d = self.generator.descendants(element.name)
AttributeError: 'NoneType' object has no attribute 'name'
```

This is with BMT 0.3.0 and https://raw.githubusercontent.com/biolink/biolink-model/1.3.9/biolink-model.yaml
